const PHIXO_CONTEXT = `Phixo is Ian Green’s boutique portrait studio in Montréal’s West Island, built in a basement studio setting where clients come to him and the studio does the work. Ian grew up in Yorkton, Saskatchewan, and he studied digital photography at Algonquin College in Ottawa, then spent 10+ years in IT doing cloud and identity systems work, including high-stakes Microsoft 365 and Entra ID / government-style environments where correctness, access control, and trust are not optional. Photography didn’t disappear during that chapter; it stayed in the background until his partner encouraged him to come back to it properly. He is now building Phixo from zero in the West Island after moving from Ottawa, as an anglophone in a bilingual city, with one paid session completed so far and no established local network or public review base yet. Phase 1 for Phixo is therefore a lean, milestone-based building phase rather than a calendar-based plan: the work is outreach and portfolio proof across all three lanes until there are enough real sessions and genuine reviews that a stranger can find the studio confidently. The core belief Ian writes from and shoots by is that most people aren’t afraid of cameras; they’re afraid of being misrepresented, walking away with a portrait that doesn’t match who they are. Phixo exists to solve that exact fear through a process that feels calm, collaborative, and controlled rather than performative.

What Phixo is, in practice, is a studio-only, tethered workflow designed for real-time safety and adjustment. Ian shoots tethered so clients can see their images on a screen during the session, and he collaborates with them in real time rather than delivering results as a surprise after the fact. The goal is not rigid posing for performance; it’s guided, shared review so clients can adjust alongside Ian until the outcome is something they recognize as themselves. The studio is intentionally set up so nervous clients aren’t forced to “figure it out” and confident clients aren’t slowed down; the environment is controlled, the direction is steady, and the feedback loop is immediate.

Phixo serves three client lanes, and they are equal in priority because each lane represents a different kind of pivotal moment people want to be seen accurately. Lane 1 is Career and Authority for professionals in transition who need LinkedIn/headshots/executive portraits that match where they’re headed, not where they’ve already been. These clients fear misalignment: their current professional image doesn’t reflect their capability or their next chapter, and they’ve seen corporate headshots that look like documentation instead of credible presence. Ian’s tethered review is built to let them measure their portrait against their actual goal in real time, so they can adjust while the session is happening rather than hoping the result will land. Lane 2 is Personal Identity and Confidence for graduates, creatives, and young women marking milestone moments or seeking confidence portraits that feel unmistakably like them. This is the most comfort-sensitive lane: before it can feel good, the session must feel safe, and Ian reads the booking form’s comfort question before every session in this lane and adapts his approach accordingly. The fear here is not just being uncomfortable in front of a camera; it’s not recognizing themselves afterward because of over-softened, over-corrected, or generic retouching. Lane 3 is Family and Legacy for families and couples who want to preserve a real moment, and the core fear is artificiality, stiff forced poses, and everyone appearing locked into “performing a family.” Ian manages group dynamics before the session begins so the coordination is natural instead of rigid, and the tethered screen turns the session into a shared experience rather than a guessing game.

Pricing at Phixo is simple and anchored around the Signature Session, designed to keep the client decision straightforward during Phase 1 while still moving the average revenue naturally through add-ons. The Signature Session is $175 CAD for a 30-minute guided studio session that delivers 10 retouched images through an online gallery for selection and download. Extra images are $40 each or 3 for $99, all proofs are $149 for the full session download of all light-corrected, unretouched proofs with a personal-use license, and rush turnaround (delivery within 48 hours instead of the standard 7–10 business days) is $99. For on-location team work, Ian can do a half-day on-site package from $1,200 (with up to 10 team members and a project-quoted scope), but this is opportunistic and not the core model. His long-run target is an AOV of $220–$250 where the Signature Session remains the anchor and the gap is closed through add-ons that clients choose because the session went well, not because the conversation is engineered.

Ian’s brand voice is warm without gushing, confident without being corporate, and it sounds like a person wrote it rather than a funnel. The delivery allows small rhythmic imperfections, and vulnerability is allowed as long as it doesn’t undercut competence; he can be honest that Phixo is still being built while still making it clear he knows how to run a session well. He avoids a specific set of words that signal over-promising or performance: stunning, perfect, gorgeous, amazing, journey, transformation, flawless, “look amazing,” best self, cherish forever, dream session, and magical. In their place, he reaches for words like guided, steady, real, intentional, genuine, grounded, collaborative, natural, honest, calm, controlled, and present. He also follows a practical writing rule: treat every line as describing the actual studio experience, because clients are not buying a slogan; they’re buying safety, guidance, and recognition in an intentionally run process.

In Phase 1, Ian’s acquisition approach matches his constraints and his starting point in Montreal. He posts in Facebook community groups as Ian (not as “Phixo”), because he’s an introvert who won’t do networking events, won’t cold-call businesses, and won’t lean on chambers-of-commerce style outreach. When someone in a group mentions a milestone, he does direct personal outreach as a human connection rather than a sales pitch. He also uses selective TFP collaborations to fill portfolio gaps across the three lanes so he can build enough real proof to make passive channels viable later. After every session, he asks for a referral in a genuine, simple way, because referrals from day one are the fastest path to Phase 1 milestones in a city where nobody yet knows him. This is also why he avoids paid advertising until portfolio proof exists; during Phase 1, spending on passive channels without enough review and depth would waste time and money. The model is digital-first: it’s social, DMs, and community posts, but it’s also studio-only, with no outdoor travel sessions and no “come to you” assumption. Being an anglophone in a bilingual market is part of the context: his content and booking experience are built to feel welcoming and clear without performing.

Ian’s strengths are not generic “photography skills”; they come from his IT background and how it shows up in operations and workflow. He has 10+ years of experience in cloud infrastructure, APIs, automation, RAG pipelines, and identity systems—capabilities that most photographers do not have. That means he can build and maintain the systems behind Phixo rather than relying on fragile processes, and he thinks patiently in long games because his six-figure day job at the federal government provides stability and removes financial desperation from day-to-day decisions. He pairs that systems mindset with the photography side: a dedicated, controlled basement studio, a tethered workflow that turns nervousness into guided adjustment, and a pace that protects quality while still stacking progress toward Phase 1.

The roadmap from studio to SaaS clarifies what Phase 1 is actually funding. Phase 1 (Years 1–3) is the cash-flow engine years: run lean at 10–12 sessions per month, dial in the tethered workflow, lighting consistency, booking and client experience, and stack cash reserves while building enough real proof to earn reviews and referrals. Phase 2 (Years 4–6) adds event photography and premium photo booths, using the firsthand frustration and inefficiencies Ian encounters in that industry to identify the SaaS product gap worth building. In that phase, corporate events can pay $1,500+ per day with 60–70% margins, and he uses the Phase 1 reserves plus event profits to bootstrap the software build without betting the house. Phase 3 (Years 7–10) is where he scales the SaaS for event photographers and booth owners, targeting 1,700 active users at $49/month, aiming for $1M ARR by Year 10, and preserving the portrait studio as a grounded, low-overhead constant while the software becomes the bigger asset. The exit possibility—$5M–$8M—exists as a potential outcome of that stacked sequence, but the immediate reality is that every Phase 1 decision, every generated question, and every piece of studio content needs to respect where the business is today: a studio being built in Montreal’s West Island, with one paid session completed, clients coming to him, and the entire process designed to make people feel accurately seen.
`;

module.exports = { PHIXO_CONTEXT };

